"""Criar tabela pessoa

Revision ID: 040c3afde55e
Revises: 2ab97b37e945
Create Date: 2024-09-15 15:30:46.981466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040c3afde55e'
down_revision = '2ab97b37e945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('main_whatsapp', sa.String(length=13), nullable=False),
    sa.Column('second_whatsapp', sa.String(length=13), nullable=True),
    sa.Column('about_you', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
