"""More than one photo

Revision ID: 0eb1f1a7b3ae
Revises: f5a32572ecba
Create Date: 2024-12-09 00:17:05.095482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0eb1f1a7b3ae'
down_revision = 'f5a32572ecba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation_history')
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('photos')

    op.create_table('donation_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='donation_history_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
