"""More than one photo

Revision ID: 0eb1f1a7b3ae
Revises: f5a32572ecba
Create Date: 2024-12-09 00:17:05.095482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0eb1f1a7b3ae'
down_revision = 'f5a32572ecba'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('photos')
    # ### end Alembic commands ###
