"""recriar tabela de pets

Revision ID: 4cd96c267212
Revises: d9fd057c784f
Create Date: 2024-11-19 12:43:55.977736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cd96c267212'
down_revision = 'd9fd057c784f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.add_column(
            sa.Column('veterinary_care', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('temperament', sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column('about', sa.String(length=500), nullable=True))
        batch_op.drop_constraint('pet_ibfk_1', type_='foreignkey')
        batch_op.drop_column('which_special_needs')
        batch_op.drop_column('castrated')
        batch_op.drop_column('vaccinated')
        batch_op.drop_column('special_needs')
        batch_op.drop_column('availability')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('availability', mysql.TINYINT(
            display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('special_needs', mysql.TINYINT(
            display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vaccinated', mysql.TINYINT(
            display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('castrated', mysql.TINYINT(
            display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('which_special_needs',
                            mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key(
            'pet_ibfk_1', 'address', ['address_id'], ['id'])
        batch_op.drop_column('about')
        batch_op.drop_column('temperament')
        batch_op.drop_column('veterinary_care')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
    # ### end Alembic commands ###
