"""Adiciona campo avatar

Revision ID: 83a95b30e6ea
Revises: fc86dcc8b1b5
Create Date: 2024-09-22 17:51:58.494227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83a95b30e6ea'
down_revision = 'fc86dcc8b1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('avatar', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('avatar')
    # ### end Alembic commands ###
