"""Criar tabela pet

Revision ID: a08da7e68e9e
Revises: 040c3afde55e
Create Date: 2024-09-15 15:36:13.655288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a08da7e68e9e'
down_revision = '040c3afde55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('species', sa.String(length=20), nullable=False),
                    sa.Column('breed', sa.String(length=100), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('adopted', sa.Boolean(), nullable=False),
                    sa.Column('vaccinated', sa.Boolean(), nullable=False),
                    sa.Column('castrated', sa.Boolean(), nullable=False),
                    sa.Column('size', sa.Float(), nullable=False),
                    sa.Column('gender', sa.String(length=1), nullable=False),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('availability', sa.Boolean(), nullable=False),
                    sa.Column('special_needs', sa.Boolean(), nullable=False),
                    sa.Column('which_special_needs', sa.String(
                        length=255), nullable=True),
                    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
