"""Criar tabela adoção

Revision ID: ba8de5a8e5c8
Revises: 407d6be40cc3
Create Date: 2024-09-15 15:48:37.137731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba8de5a8e5c8'
down_revision = '407d6be40cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_history',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('person_id', sa.Integer(), nullable=True),
                    sa.Column('pet_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
                    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adoption_history')
    # ### end Alembic commands ###
