"""Remover campo número

Revision ID: d3e107bfac30
Revises: 750d1ac1e9a3
Create Date: 2024-10-21 11:27:18.041982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3e107bfac30'
down_revision = '750d1ac1e9a3'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
