"""Alterar tipo do campo size

Revision ID: d9fd057c784f
Revises: d3e107bfac30
Create Date: 2024-10-21 11:31:20.679755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9fd057c784f'
down_revision = 'd3e107bfac30'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('size',
                              existing_type=mysql.FLOAT(),
                              type_=sa.String(length=1),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('size',
                              existing_type=sa.String(length=1),
                              type_=mysql.FLOAT(),
                              existing_nullable=False)
    # ### end Alembic commands ###
