"""Codigo de email

Revision ID: da6512d216f6
Revises: 0eb1f1a7b3ae
Create Date: 2024-12-09 23:37:53.406099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da6512d216f6'
down_revision = '0eb1f1a7b3ae'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('email_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('email_code')
    # ### end Alembic commands ###
