"""cria tabela post

Revision ID: e2dc50b65e24
Revises: 9a9cd42b5674
Create Date: 2025-06-05 15:42:11.546350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2dc50b65e24'
down_revision = '9a9cd42b5674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('state', sa.String(length=2), nullable=False),
                    sa.Column('city', sa.String(length=100), nullable=False),
                    sa.Column('neighborhood', sa.String(
                        length=100), nullable=False),
                    sa.Column('street', sa.String(length=100), nullable=False),
                    sa.Column('text', sa.String(length=500), nullable=False),
                    sa.Column('main_photo', sa.String(
                        length=500), nullable=True),
                    sa.Column('lost_animal', sa.Boolean(), nullable=False),
                    sa.Column('veterinary_event',
                              sa.Boolean(), nullable=False),
                    sa.Column('parterns_campaign',
                              sa.Boolean(), nullable=False),
                    sa.Column('person_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('post')
    # ### end Alembic commands ###
