"""adicionar compo de id de pessoa

Revision ID: f5a32572ecba
Revises: 4cd96c267212
Create Date: 2024-11-20 18:04:28.217426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5a32572ecba'
down_revision = '4cd96c267212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alem
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'person', ['person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('person_id')
    # ### end Alembic commands ###
