"""Atualização do tamanho da senha

Revision ID: fc86dcc8b1b5
Revises: ba8de5a8e5c8
Create Date: 2024-09-17 01:49:33.385332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc86dcc8b1b5'
down_revision = 'ba8de5a8e5c8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
